import { Metadata } from 'next';

import Navbar from '@/app/components/navbar';

import "./globals.css";

interface LayoutProps {
    children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps) {
    return (
      <html lang="en">
          <body className="bg-background min-h-screen text-foreground font-geist flex flex-col">
              <Navbar />
              {children}
          </body>
      </html>
    );
}
